# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  banki-api:
    image: banki-api
    build:
      context: .
      dockerfile: Banki.API/Dockerfile
    ports:
      - 5087:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
